export interface OperatorDef {
  id: string;
  name: string;
  role: string;
  side: 'atk' | 'def';
  color: number;
  ability: string;
  gadgetName: string;
  gadgetType: string;
  charges: number;
  cooldown: number;
  speed: number; // 1 (heavy/slow), 2 (medium), 3 (fast/light)
  armor: number; // 3 (high armor), 2 (medium), 1 (light armor)
  playstyle: string;
}

export const ATTACKERS: OperatorDef[] = [
  {
    id: 'sledge',
    name: 'Sledge',
    role: 'Soft Breach / Vertical',
    side: 'atk',
    color: 0x5a8fb8,
    ability: 'Breaching Hammer — swing tactical sledgehammer to instantly obliterate barricades, soft walls, and floors for vertical destruction.',
    gadgetName: 'Breaching Hammer',
    gadgetType: 'breach_hammer',
    charges: 20,
    cooldown: 0.6,
    speed: 2,
    armor: 2,
    playstyle: 'Take control above or beside the objective and smash soft surfaces to expose defender angles.'
  },
  {
    id: 'thatcher',
    name: 'Thatcher',
    role: 'Anti-Gadget / Support',
    side: 'atk',
    color: 0x4a7eb8,
    ability: 'EMP Grenades — throws electromagnetic pulse grenade that disables and destroys all defender electronics, cameras, traps, and jammers.',
    gadgetName: 'EG MKO-EMP Grenade',
    gadgetType: 'emp_grenade',
    charges: 3,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Throw EMP grenades at fortified walls to disable defender batteries and jammers before the hard breach.'
  },
  {
    id: 'ash',
    name: 'Ash',
    role: 'Entry / Soft Breach',
    side: 'atk',
    color: 0xd9534f,
    ability: 'Breaching Rounds — fires rocket-propelled high-explosive round from M120 launcher that disintegrates barricades and soft walls from safe range.',
    gadgetName: 'M120 CREM Breaching Round',
    gadgetType: 'breach_rounds',
    charges: 2,
    cooldown: 3.0,
    speed: 3,
    armor: 1,
    playstyle: 'Fast and aggressive entry specialist. Demolishes obstacles and maintains constant forward pressure.'
  },
  {
    id: 'thermite',
    name: 'Thermite',
    role: 'Hard Breach',
    side: 'atk',
    color: 0xe67e22,
    ability: 'Exothermic Charge — places heavy Brimstone thermal pack on reinforced metal walls; burns with sizzling sparks then rips open a massive entryway.',
    gadgetName: 'Brimstone BC-3 Exothermic Charge',
    gadgetType: 'exothermic_charge',
    charges: 2,
    cooldown: 8.0,
    speed: 2,
    armor: 2,
    playstyle: 'Stay alive, reach the crucial reinforced perimeter, blow open the reinforced wall, and execute the plant.'
  },
  {
    id: 'twitch',
    name: 'Twitch',
    role: 'Anti-Gadget / Intel',
    side: 'atk',
    color: 0x3498db,
    ability: 'Shock Drone — deploys or switches to a high-tech shock drone armed with a live-fire mounted gun to destroy defender gadgets and shoot enemies.',
    gadgetName: 'RSD Model 1 Shock Drone',
    gadgetType: 'shock_drone',
    charges: 2,
    cooldown: 5.0,
    speed: 2,
    armor: 2,
    playstyle: 'Drive shock drone quietly through defender sites to destroy batteries, traps, and cameras before the assault.'
  },
  {
    id: 'montagne',
    name: 'Montagne',
    role: 'Shield / Intel / Support',
    side: 'atk',
    color: 0x2980b9,
    ability: 'Extendable Shield — expands heavy "Le Roc" ballistic shield to full standing height, giving 100% frontal bullet immunity.',
    gadgetName: 'Le Roc Extendable Shield',
    gadgetType: 'extend_shield',
    charges: 1,
    cooldown: 1.0,
    speed: 1,
    armor: 3,
    playstyle: 'Lead the advance, absorb incoming crossfire, provide moving cover and ping positions for teammates.'
  },
  {
    id: 'glaz',
    name: 'Glaz',
    role: 'Front Line / Long Range',
    side: 'atk',
    color: 0x27ae60,
    ability: 'Flip Sight — flips high-contrast HDS thermal optic onto sniper rifle; highlights defenders in bright yellow through smoke screens.',
    gadgetName: 'HDS Flip Sight',
    gadgetType: 'flip_sight',
    charges: 1,
    cooldown: 0.5,
    speed: 2,
    armor: 2,
    playstyle: 'Deploy smoke around the objective or plant zone and eliminate defenders through the smoke screen.'
  },
  {
    id: 'fuze',
    name: 'Fuze',
    role: 'Utility Clear / Area Control',
    side: 'atk',
    color: 0xc0392b,
    ability: 'Cluster Charge — plants APM-6 "Matryoshka" charge onto barricade, floor, or soft wall that drills through and fires 5 bouncing explosive pucks.',
    gadgetName: 'APM-6 Matryoshka',
    gadgetType: 'cluster_charge',
    charges: 4,
    cooldown: 6.0,
    speed: 1,
    armor: 3,
    playstyle: 'Plant cluster charges on ceilings above objective or windows to clear defender traps and anchors.'
  },
  {
    id: 'blitz',
    name: 'Blitz',
    role: 'Shield / Entry',
    side: 'atk',
    color: 0xf39c12,
    ability: 'Flash Shield — triggers high-intensity strobe flash array on tactical shield, blinding and disorienting enemies within 6 meters.',
    gadgetName: 'G52-Tactical Flash Shield',
    gadgetType: 'flash_shield',
    charges: 4,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Sprint directly at isolated defenders, trigger flash burst to blind them, and neutralize them with melee or hipfire.'
  },
  {
    id: 'iq',
    name: 'IQ',
    role: 'Intel / Anti-Gadget',
    side: 'atk',
    color: 0x9b59b6,
    ability: 'Electronics Detector — activates wrist-mounted RED Mk III sensor; detects and outlines all enemy electronic gadgets through solid walls.',
    gadgetName: 'RED Mk III Spectre',
    gadgetType: 'electronics_detector',
    charges: 1,
    cooldown: 0.5,
    speed: 3,
    armor: 1,
    playstyle: 'Scan walls and doorways to locate Pulse, Kapkan EDDs, Valkyrie cameras, and defuser equipment through cover.'
  },
  {
    id: 'buck',
    name: 'Buck',
    role: 'Soft Breach / Vertical',
    side: 'atk',
    color: 0x16a085,
    ability: 'Skeleton Key — toggles underbarrel masterkey 12-gauge shotgun on assault rifle for rapid soft-surface and floor shredding.',
    gadgetName: 'SK 4-12 Skeleton Key',
    gadgetType: 'skeleton_key',
    charges: 1,
    cooldown: 0.4,
    speed: 2,
    armor: 2,
    playstyle: 'Switch seamlessly between rifle and breaching shotgun to blast ceilings and floors from above or below.'
  },
  {
    id: 'blackbeard',
    name: 'Blackbeard',
    role: 'Front Line / Angle Holder',
    side: 'atk',
    color: 0x8e44ad,
    ability: 'Rifle Shield — snaps transparent multi-ply polycarbonate ballistic shield onto rifle to absorb incoming headshots while peeking.',
    gadgetName: 'TARS Mk 0 Transparent Shield',
    gadgetType: 'rifle_shield',
    charges: 2,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Rappel outside high windows or hold tight sightlines with facial bullet protection.'
  },
  {
    id: 'capitao',
    name: 'Capitão',
    role: 'Support / Execute / Area Control',
    side: 'atk',
    color: 0xd35400,
    ability: 'Tactical Crossbow — fires micro smoke screens or asphyxiating fire bolts that blanket areas in lethal flames to deny rotations.',
    gadgetName: 'TAC Mk0 Crossbow',
    gadgetType: 'tactical_crossbow',
    charges: 4,
    cooldown: 2.0,
    speed: 3,
    armor: 1,
    playstyle: 'Fire smoke bolts to cover the plant and shoot asphyxiating fire to flush out defenders hiding behind cover.'
  },
  {
    id: 'hibana',
    name: 'Hibana',
    role: 'Hard Breach',
    side: 'atk',
    color: 0xe74c3c,
    ability: 'X-KAIROS — launches 6 magnetic thermal pellets that attach to reinforced walls/hatches and remotely detonate into clean sightlines.',
    gadgetName: 'X-KAIROS 40mm Launcher',
    gadgetType: 'x_kairos',
    charges: 3,
    cooldown: 5.0,
    speed: 3,
    armor: 1,
    playstyle: 'Ranged hard breacher. Pop hatches and cut kill holes into reinforced walls from a safe vantage point.'
  },
  {
    id: 'jackal',
    name: 'Jackal',
    role: 'Roam Clear / Intel',
    side: 'atk',
    color: 0x2c3e50,
    ability: 'Eyenox — toggles tracking optics that highlight fresh defender footprints on the floor; scanning footsteps periodically pings their live location.',
    gadgetName: 'Eyenox Model III',
    gadgetType: 'eyenox',
    charges: 3,
    cooldown: 8.0,
    speed: 2,
    armor: 2,
    playstyle: 'Hunt down roaming defenders by finding and scanning their footsteps, flushing them back to site.'
  },
  {
    id: 'ying',
    name: 'Ying',
    role: 'Entry / Execute',
    side: 'atk',
    color: 0x1abc9c,
    ability: 'Candela — throws or rolls flash device that detonates in a rapid cluster of 7 blinding strobe flashes while Ying wears protective goggles.',
    gadgetName: 'Candela Flash Cluster',
    gadgetType: 'candela',
    charges: 3,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Roll Candelas into the objective room, blinding every defender, then push with immunity.'
  },
  {
    id: 'zofia',
    name: 'Zofia',
    role: 'Front Line / Utility',
    side: 'atk',
    color: 0x95a5a6,
    ability: 'KS79 Lifeline — double-barrel launcher firing instant contact impact breach shells and concussion proximity grenades.',
    gadgetName: 'KS79 Lifeline Launcher',
    gadgetType: 'ks79_lifeline',
    charges: 4,
    cooldown: 2.5,
    speed: 2,
    armor: 2,
    playstyle: 'Blow open soft barriers instantly with impact rounds and disorient defenders around corners with concussion shells.'
  },
  {
    id: 'dokkaebi',
    name: 'Dokkaebi',
    role: 'Intel / Disruption',
    side: 'atk',
    color: 0x34495e,
    ability: 'Logic Bomb — injects military virus into defender phones; emits loud buzzing ringtones revealing defender audio positions and blocking cams.',
    gadgetName: 'Logic Bomb Cyber Virus',
    gadgetType: 'logic_bomb',
    charges: 2,
    cooldown: 12.0,
    speed: 2,
    armor: 2,
    playstyle: 'Activate before pushing a room to hear exactly where defenders are hiding and force them to turn off their phones.'
  },
  {
    id: 'lion',
    name: 'Lion',
    role: 'Intel / Support',
    side: 'atk',
    color: 0xf1c40f,
    ability: 'EE-ONE-D — triggers global aerial drone sonar scan; any defender moving during the scan is immediately revealed with live red outline.',
    gadgetName: 'EE-ONE-D Sonar Drone',
    gadgetType: 'ee_one_d',
    charges: 3,
    cooldown: 15.0,
    speed: 2,
    armor: 2,
    playstyle: 'Coordinate scan with team pushes or defuser plant so defenders are trapped: move and be wallhacked, or stand still and be pre-fired.'
  },
  {
    id: 'finka',
    name: 'Finka',
    role: 'Support',
    side: 'atk',
    color: 0x7f8c8d,
    ability: 'Adrenal Surge — activates team-wide nanobot surge providing instant +25 HP boost, reduced weapon recoil, and quick downed ally revival.',
    gadgetName: 'Adrenal Nanobot Surge',
    gadgetType: 'adrenal_surge',
    charges: 3,
    cooldown: 14.0,
    speed: 2,
    armor: 2,
    playstyle: 'Pop adrenal surge during heavy gunfights or team pushes to give every attacker maximum survivability and laser accuracy.'
  },
  {
    id: 'maverick',
    name: 'Maverick',
    role: 'Hard Breach / Support',
    side: 'atk',
    color: 0xd35400,
    ability: 'Breaching Torch — silent oxyacetylene blowtorch that melts surgical holes through soft surfaces and reinforced walls.',
    gadgetName: 'Suri Torch DHI',
    gadgetType: 'breaching_torch',
    charges: 1,
    cooldown: 0.5,
    speed: 3,
    armor: 1,
    playstyle: 'Silently burn peek holes through reinforced walls to snipe anchors, or burn bottom lines to open crawl spaces.'
  },
  {
    id: 'nomad',
    name: 'Nomad',
    role: 'Flank Watch / Area Control',
    side: 'atk',
    color: 0xe67e22,
    ability: 'Airjab — launches sticky repulsion mines that adhere to walls; detonates with violent kinetic air blast knocking defenders flat on their backs.',
    gadgetName: 'Airjab Repulsion Launcher',
    gadgetType: 'airjab',
    charges: 3,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Stick Airjabs behind your team on stairwells and doorways to completely deny defender flanks and runouts.'
  },
  {
    id: 'gridlock',
    name: 'Gridlock',
    role: 'Area Control / Execute',
    side: 'atk',
    color: 0xbdc3c7,
    ability: 'Trax Stingers — throws mechanical canister that deploys an expanding web of barbed steel caltrops, severely slowing and damaging defenders.',
    gadgetName: 'Trax Stingers Caltrops',
    gadgetType: 'trax_stingers',
    charges: 3,
    cooldown: 5.0,
    speed: 1,
    armor: 3,
    playstyle: 'Drop Trax Stingers across entry doors after planting the defuser to prevent defenders from retaking the room.'
  },
  {
    id: 'nokk',
    name: 'Nøkk',
    role: 'Stealth / Entry',
    side: 'atk',
    color: 0x2c3e50,
    ability: 'HEL Presence Reduction — activates HEL device; muffles footstep sounds completely and erases presence from defender surveillance cameras.',
    gadgetName: 'HEL Presence Reduction Device',
    gadgetType: 'hel_reduction',
    charges: 1,
    cooldown: 8.0,
    speed: 2,
    armor: 2,
    playstyle: 'Infiltrate quietly through camera zones without triggering alarms, catching anchoring defenders off-guard.'
  },
  {
    id: 'amaru',
    name: 'Amaru',
    role: 'Vertical Entry / Front Line',
    side: 'atk',
    color: 0x16a085,
    ability: 'Garra Hook — fires motorized high-tension grapple hook that propels her directly into elevated 2nd-floor windows with an instant kick breach.',
    gadgetName: 'Garra Hook Grapple',
    gadgetType: 'garra_hook',
    charges: 4,
    cooldown: 8.0,
    speed: 2,
    armor: 2,
    playstyle: 'Rapid vertical infiltration. Grapple straight into 2F windows within seconds to create unexpected early entry.'
  },
  {
    id: 'kali',
    name: 'Kali',
    role: 'Anti-Gadget / Long Range',
    side: 'atk',
    color: 0x2980b9,
    ability: 'LV Explosive Lance — underbarrel lance that embeds into reinforced walls and explodes on both sides, destroying gadgets without opening hard wall.',
    gadgetName: 'LV Explosive Lance',
    gadgetType: 'explosive_lance',
    charges: 3,
    cooldown: 5.0,
    speed: 2,
    armor: 2,
    playstyle: 'Clear Mute jammers and Bandit shock batteries safely from a distance to enable teammates to hard breach.'
  },
  {
    id: 'iana',
    name: 'Iana',
    role: 'Intel / Entry',
    side: 'atk',
    color: 0xecf0f1,
    ability: 'Gemini Replicator — deploys a controllable holographic duplicate that sprints forward to probe rooms, trigger traps, and bait defender fire.',
    gadgetName: 'Gemini Replicator Hologram',
    gadgetType: 'gemini_replicator',
    charges: 1,
    cooldown: 12.0,
    speed: 2,
    armor: 2,
    playstyle: 'Send hologram into dangerous rooms first to scout enemy angles and waste defender ammunition.'
  },
  {
    id: 'ace',
    name: 'Ace',
    role: 'Hard Breach',
    side: 'atk',
    color: 0x0284c7,
    ability: 'SELMA Aqua Breacher — throws sequential hydraulic breach charges that stick to reinforced walls and roll down to carve wide entry openings.',
    gadgetName: 'SELMA Aqua Breacher',
    gadgetType: 'selma_breacher',
    charges: 3,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Throw SELMA canisters from range onto reinforced walls to open up massive breach corridors.'
  },
  {
    id: 'zero',
    name: 'Zero',
    role: 'Intel / Anti-Gadget',
    side: 'atk',
    color: 0x27ae60,
    ability: 'Argus Cameras — shoots two-way drill cameras that pierce solid walls and barricades, offering surveillance on both sides with laser zap.',
    gadgetName: 'Argus Camera Launcher',
    gadgetType: 'argus_camera',
    charges: 4,
    cooldown: 4.0,
    speed: 3,
    armor: 1,
    playstyle: 'Shoot Argus cams through reinforced ceilings or walls into the bomb room to watch defenders and zap utility.'
  },
  {
    id: 'flores',
    name: 'Flores',
    role: 'Utility Clear / Support',
    side: 'atk',
    color: 0xe67e22,
    ability: 'RCE-Ratero Charge — drives remote explosive bomb drone; accelerates, turns bulletproof, and detonates in a massive 5m demolition blast.',
    gadgetName: 'RCE-Ratero Explosive Drone',
    gadgetType: 'ratero_drone',
    charges: 4,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Drive Ratero drones into defender bunkered positions to destroy bulletproof shields and force defenders to abandon cover.'
  },
  {
    id: 'osa',
    name: 'Osa',
    role: 'Support / Angle Control',
    side: 'atk',
    color: 0x1abc9c,
    ability: 'Talon-8 Clear Shield — deploys transparent waist-high bulletproof ballistic shield on doorways, windows, or floor as custom fortified cover.',
    gadgetName: 'Talon-8 Clear Shield',
    gadgetType: 'clear_shield',
    charges: 2,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Place transparent shields in entryways or windows to peek defenders with full frontal protection.'
  },
  {
    id: 'sens',
    name: 'Sens',
    role: 'Area Control / Execute',
    side: 'atk',
    color: 0x2ecc71,
    ability: 'R.O.U. Projector — rolls wheel device that deploys micro-projectors casting a 15-meter tall green holographic light wall blocking sightlines.',
    gadgetName: 'R.O.U. Projector System',
    gadgetType: 'rou_projector',
    charges: 3,
    cooldown: 5.0,
    speed: 3,
    armor: 1,
    playstyle: 'Roll holographic screen across defender crossfires to mask defuser planting and advance teammates safely.'
  },
  {
    id: 'grim',
    name: 'Grim',
    role: 'Intel / Area Control',
    side: 'atk',
    color: 0xf39c12,
    ability: 'Kawan Hive — fires canisters from launcher that release an aerial swarm of micro-bots; any defender touching the swarm is tracked.',
    gadgetName: 'Kawan Hive Launcher',
    gadgetType: 'kawan_hive',
    charges: 5,
    cooldown: 3.0,
    speed: 3,
    armor: 1,
    playstyle: 'Saturate doorways and corners with tracking swarms before pushing to expose any waiting defenders.'
  },
  {
    id: 'brava',
    name: 'Brava',
    role: 'Anti-Gadget / Intel',
    side: 'atk',
    color: 0x9b59b6,
    ability: 'Kludge Drone — optical hacking drone; fires electromagnetic laser beam to hack defender traps, cameras, or jammers and turn them against defense.',
    gadgetName: 'Kludge Hacking Drone',
    gadgetType: 'kludge_drone',
    charges: 2,
    cooldown: 8.0,
    speed: 2,
    armor: 2,
    playstyle: 'Infiltrate site with Kludge drone to hack Kapkan EDD traps and Maestro turrets, converting them to kill defenders.'
  },
  {
    id: 'ram',
    name: 'Ram',
    role: 'Vertical / Soft Breach',
    side: 'atk',
    color: 0x34495e,
    ability: 'BU-GI Auto-Breacher — deploys heavy autonomous armored tank that rolls forward, shredding soft floors, furniture, and barricades into splinters.',
    gadgetName: 'BU-GI Auto-Breacher',
    gadgetType: 'bu_gi_breacher',
    charges: 3,
    cooldown: 5.0,
    speed: 1,
    armor: 3,
    playstyle: 'Launch BU-GI tank across the 2nd floor to open up massive floor destruction onto the defenders below.'
  },
  {
    id: 'deimos',
    name: 'Deimos',
    role: 'Roam Hunt / Intel',
    side: 'atk',
    color: 0xc0392b,
    ability: 'DeathMARK — launches tracking nano-drone that locks onto a targeted defender, granting live red silhouette tracking in a lethal 1v1 duel.',
    gadgetName: 'DeathMARK Tracker Drone',
    gadgetType: 'deathmark',
    charges: 3,
    cooldown: 12.0,
    speed: 2,
    armor: 2,
    playstyle: 'Lock onto roaming defenders and hunt them down with wallhack tracking while forcing a direct gunfight.'
  },
  {
    id: 'striker',
    name: 'Striker',
    role: 'Support / Flex',
    side: 'atk',
    color: 0x16a085,
    ability: 'Flexible Utility — adaptable tactical operative equipped with dual secondary gadgets (Hard Breach Charge + EMP Impact) to fill any team gap.',
    gadgetName: 'Adaptable Breach Kit',
    gadgetType: 'flexible_utility',
    charges: 2,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Adapt to any team composition by bringing both hard breach capability and electronic gadget denial.'
  },
  {
    id: 'rauora',
    name: 'Rauora',
    role: 'Support / Area Control',
    side: 'atk',
    color: 0x2980b9,
    ability: 'D.O.M. Panels — deploys interlocking tactical ballistic panels to establish fortified attack angles and safe staging positions.',
    gadgetName: 'D.O.M. Tactical Panel',
    gadgetType: 'dom_panels',
    charges: 2,
    cooldown: 5.0,
    speed: 2,
    armor: 2,
    playstyle: 'Create secure fortified staging positions right outside the bomb room during the final execute.'
  },
  {
    id: 'solid_snake',
    name: 'Solid Snake',
    role: 'Stealth / Front Line',
    side: 'atk',
    color: 0x2c3e50,
    ability: 'Stealth Infiltration — activates OctoCamo stealth suit (90% translucent cloak) and deploys Chaff Grenade disabling cameras and radar.',
    gadgetName: 'OctoCamo & Chaff Device',
    gadgetType: 'stealth_infil',
    charges: 2,
    cooldown: 15.0,
    speed: 3,
    armor: 1,
    playstyle: 'Sneak into objective undetected through gaps in defender surveillance and eliminate key anchors with surprise strikes.'
  },
  {
    id: 'denari',
    name: 'Denari',
    role: 'Area Control / Support',
    side: 'atk',
    color: 0x8e44ad,
    ability: 'Acoustic Shock Repulsor — deploys high-pressure perimeter device that concusses and knocks back defenders pushing through corridors.',
    gadgetName: 'Acoustic Repulsor Pylon',
    gadgetType: 'area_control',
    charges: 2,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Deploy repulsors to lock down defender rotation hallways and safeguard the planted defuser.'
  }
];

export const DEFENDERS: OperatorDef[] = [
  {
    id: 'smoke',
    name: 'Smoke',
    role: 'Anchor / Area Denial',
    side: 'def',
    color: 0x7f8c8d,
    ability: 'Remote Gas Grenades — throws sticky canisters releasing thick yellow toxic compound that deals 25 dmg/sec and denies entry for 10 seconds.',
    gadgetName: 'Remote Gas Canister (Babes)',
    gadgetType: 'gas_grenade',
    charges: 3,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Wait out the round, monitor entry doorways, and burn attacker clock late in the round with toxic gas clouds.'
  },
  {
    id: 'mute',
    name: 'Mute',
    role: 'Anti-Gadget / Support',
    side: 'def',
    color: 0x34495e,
    ability: 'Signal Disruptors — deploys GC90 jammers that create a 4m electromagnetic dead zone, disabling attacker drones, breach charges, and gadgets.',
    gadgetName: 'GC90 Signal Disruptor Jammer',
    gadgetType: 'signal_disruptor',
    charges: 4,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Place jammers near site doorways during prep phase to kill recon drones, and behind reinforced walls to stop Thermite.'
  },
  {
    id: 'castle',
    name: 'Castle',
    role: 'Support / Site Setup',
    side: 'def',
    color: 0x8e44ad,
    ability: 'Armor Panels — deploys bulletproof, melee-resistant Kevlar barricade panels that require heavy explosive breach or 12 melee hits to break.',
    gadgetName: 'UTP1-Duster Armor Panel',
    gadgetType: 'armor_panel',
    charges: 4,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Lock down critical exterior windows and doorways to force attackers to waste precious explosive utility.'
  },
  {
    id: 'pulse',
    name: 'Pulse',
    role: 'Roamer / Intel',
    side: 'def',
    color: 0xc0392b,
    ability: 'Cardiac Sensor — pulls up handheld heartbeat monitor that detects and displays beating hearts of nearby attackers through solid walls.',
    gadgetName: 'HB-5 Cardiac Sensor',
    gadgetType: 'cardiac_sensor',
    charges: 1,
    cooldown: 0.5,
    speed: 3,
    armor: 1,
    playstyle: 'Roam below or behind attackers, scan heartbeats through floors/walls, and blast them with C4 or shotgun through soft cover.'
  },
  {
    id: 'doc',
    name: 'Doc',
    role: 'Anchor / Support',
    side: 'def',
    color: 0x2980b9,
    ability: 'Stim Pistol — fires hypodermic darts that heal self or teammates for +40 HP, can overheal up to 140 HP, and revives downed allies from range.',
    gadgetName: 'MPD-0 Stim Pistol',
    gadgetType: 'stim_pistol',
    charges: 3,
    cooldown: 2.0,
    speed: 1,
    armor: 3,
    playstyle: 'Anchor on site, hold strong angles with high armor, and fire stim darts to keep team at maximum health.'
  },
  {
    id: 'rook',
    name: 'Rook',
    role: 'Support / Anchor',
    side: 'def',
    color: 0x3498db,
    ability: 'Armor Pack — drops duffel bag of ceramic armor plates for the whole team; grants +20 max armor and 25% damage resistance to all who pick it up.',
    gadgetName: 'R10 Armor Pack',
    gadgetType: 'armor_pack',
    charges: 1,
    cooldown: 1.0,
    speed: 1,
    armor: 3,
    playstyle: 'Drop armor pack at the start of prep phase immediately, reinforce crucial walls, and anchor the site.'
  },
  {
    id: 'jager',
    name: 'Jäger',
    role: 'Anti-Gadget / Support',
    side: 'def',
    color: 0xf39c12,
    ability: 'ADS — deploys Magpie Active Defense System on walls/floors that automatically intercepts and zaps incoming grenades and projectiles.',
    gadgetName: 'Magpie ADS Defense System',
    gadgetType: 'ads_defense',
    charges: 3,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Mount ADS devices around objective anchor spots to protect teammates from attacker frag grenades and flashbangs.'
  },
  {
    id: 'bandit',
    name: 'Bandit',
    role: 'Anti-Breach',
    side: 'def',
    color: 0xf1c40f,
    ability: 'Shock Wire — connects high-voltage car batteries to reinforced metal walls and barbed wire, shocking intruders and frying attacker breach charges.',
    gadgetName: 'CED-1 Shock Battery',
    gadgetType: 'shock_wire',
    charges: 4,
    cooldown: 2.0,
    speed: 3,
    armor: 1,
    playstyle: 'Electrify reinforced walls to prevent Thermite and Hibana from breaching. "Bandit trick" by listening for charges.'
  },
  {
    id: 'tachanka',
    name: 'Tachanka',
    role: 'Area Denial',
    side: 'def',
    color: 0xd35400,
    ability: 'Shumikha Launcher — fires bouncing incendiary grenades that ignite the floor in raging flames, denying doorways and defuser plants.',
    gadgetName: 'DP27 Shumikha Launcher',
    gadgetType: 'shumikha_fire',
    charges: 7,
    cooldown: 1.0,
    speed: 1,
    armor: 3,
    playstyle: 'Blanket corridors and entry points with incendiary fire late in the round to prevent attackers from entering the site.'
  },
  {
    id: 'kapkan',
    name: 'Kapkan',
    role: 'Trapper',
    side: 'def',
    color: 0xe74c3c,
    ability: 'Entry Denial Device (EDD) — mounts laser tripmines onto door and window frames; detonates in an instant 60-damage blast when attackers enter.',
    gadgetName: 'EDD MK.II Tripmine',
    gadgetType: 'entry_denial',
    charges: 5,
    cooldown: 1.5,
    speed: 2,
    armor: 2,
    playstyle: 'Plant EDDs on low doorframes along predictable attacker entry paths to punish rushing players.'
  },
  {
    id: 'frost',
    name: 'Frost',
    role: 'Trapper',
    side: 'def',
    color: 0x1abc9c,
    ability: 'Welcome Mats — lays heavy mechanical leg-snap traps flat on the floor; instantly injures and traps any attacker vaulting a window or doorway.',
    gadgetName: 'Sterling Mk2 Welcome Mat',
    gadgetType: 'welcome_mat',
    charges: 3,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Place Welcome Mats directly beneath barricaded windows and behind deployable shields for guaranteed catches.'
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    role: 'Intel',
    side: 'def',
    color: 0x27ae60,
    ability: 'Black Eye Cameras — throws 3 sticky gyroscopic camera spheres that adhere to any surface, giving defense 360-degree surveillance feeds.',
    gadgetName: 'Gyroscopic Black Eye Camera',
    gadgetType: 'black_eye_cam',
    charges: 3,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Toss cameras into common approach halls and exterior bushes to feed real-time intel to your roaming teammates.'
  },
  {
    id: 'caveira',
    name: 'Caveira',
    role: 'Roamer',
    side: 'def',
    color: 0x2c3e50,
    ability: 'Silent Step — activates silent stalking movement with zero footstep audio; melee attacks down attackers and can be interrogated to reveal all enemy locations.',
    gadgetName: 'Silent Step Infiltration',
    gadgetType: 'silent_step',
    charges: 1,
    cooldown: 6.0,
    speed: 3,
    armor: 1,
    playstyle: 'Lurk on the opposite floor, sneak behind isolated attackers silently, down them, and reveal the entire enemy squad.'
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Intel / Anchor',
    side: 'def',
    color: 0x16a085,
    ability: 'Yokai Drone — operates ceiling-clinging hover drone that fires ultrasonic bursts; disorients attackers and cancels defuser plant animations.',
    gadgetName: 'Yokai Hover Drone',
    gadgetType: 'yokai_drone',
    charges: 2,
    cooldown: 5.0,
    speed: 1,
    armor: 3,
    playstyle: 'Stay safe on site, monitor the bomb rooms with Yokai, and burst attackers attempting to plant the defuser.'
  },
  {
    id: 'mira',
    name: 'Mira',
    role: 'Anchor / Site Setup',
    side: 'def',
    color: 0x95a5a6,
    ability: 'Black Mirror — installs one-way bulletproof reinforced observation glass on walls; defenders see attackers clearly while attackers see black mirror.',
    gadgetName: 'Black Mirror One-Way Glass',
    gadgetType: 'black_mirror',
    charges: 2,
    cooldown: 4.0,
    speed: 1,
    armor: 3,
    playstyle: 'Place mirror on reinforced wall next to soft wall; track attackers safely through mirror, then quick-peek through soft wall for easy kills.'
  },
  {
    id: 'lesion',
    name: 'Lesion',
    role: 'Trapper / Intel',
    side: 'def',
    color: 0x2ecc71,
    ability: 'GU Mines — throws cloaked needle mines that turn invisible on the floor; poisons and slows attackers until pulled out.',
    gadgetName: 'GU Toxic Needle Mine',
    gadgetType: 'gu_mine',
    charges: 8,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Scatter GU mines along hallways leading to site; audio cues reveal exactly which direction attackers are pushing.'
  },
  {
    id: 'ela',
    name: 'Ela',
    role: 'Roamer / Crowd Control',
    side: 'def',
    color: 0x1abc9c,
    ability: 'Grzmot Mines — throws sticky concussion proximity mines above doors; detonates with dizzying deafening shockwave when attackers rush.',
    gadgetName: 'Grzmot Concussion Mine',
    gadgetType: 'grzmot_mine',
    charges: 3,
    cooldown: 2.5,
    speed: 3,
    armor: 1,
    playstyle: 'Place mines above doorways and swing around corners to eliminate attackers while they are concussed and deafened.'
  },
  {
    id: 'vigil',
    name: 'Vigil',
    role: 'Roamer / Intel Denial',
    side: 'def',
    color: 0x34495e,
    ability: 'ERC-7 — activates electronic cloaking device; completely disappears from attacker recon drones and security cameras.',
    gadgetName: 'ERC-7 Electronic Cloak',
    gadgetType: 'erc7_cloak',
    charges: 1,
    cooldown: 8.0,
    speed: 3,
    armor: 1,
    playstyle: 'Waste attacker drone time. Roam far from site while invisible to cameras, forcing attackers to clear rooms on foot.'
  },
  {
    id: 'maestro',
    name: 'Maestro',
    role: 'Anchor / Intel',
    side: 'def',
    color: 0xc0392b,
    ability: 'Evil Eye — deploys armored bulletproof remote turret camera on walls; opens shutter to fire high-energy thermal laser darts.',
    gadgetName: 'Cleo Evil Eye Turret',
    gadgetType: 'evil_eye',
    charges: 2,
    cooldown: 4.0,
    speed: 1,
    armor: 3,
    playstyle: 'Anchor in strong cover, monitor attacker approach lanes with Evil Eyes, and zap drones, gadgets, and planting attackers.'
  },
  {
    id: 'alibi',
    name: 'Alibi',
    role: 'Trapper / Deception',
    side: 'def',
    color: 0x8e44ad,
    ability: 'Prisma — deploys holographic projectors that display identical decoy illusions of Alibi; shooting or touching them pings attacker location.',
    gadgetName: 'Prisma Holographic Projector',
    gadgetType: 'prisma_decoy',
    charges: 3,
    cooldown: 3.0,
    speed: 3,
    armor: 1,
    playstyle: 'Place decoys behind windows and doorways where attackers reflexive pre-fire, pinging their positions for easy trades.'
  },
  {
    id: 'clash',
    name: 'Clash',
    role: 'Crowd Control / Support',
    side: 'def',
    color: 0x2980b9,
    ability: 'CCE Shield — full-body electrified riot shield with built-in high-voltage taser; slows attackers down by 60% and deals shock damage.',
    gadgetName: 'CCE Electro-Riot Shield',
    gadgetType: 'cce_shield',
    charges: 1,
    cooldown: 1.0,
    speed: 1,
    armor: 3,
    playstyle: 'Block doorways, zap pushing attackers with taser to slow them down, and call out their positions for teammates.'
  },
  {
    id: 'kaid',
    name: 'Kaid',
    role: 'Anti-Breach',
    side: 'def',
    color: 0xd35400,
    ability: 'Electroclaw — throws Rtila Electroclaws that attach to surfaces and electrify all reinforced walls, hatches, and barbed wire in a 3m radius.',
    gadgetName: 'Rtila Electroclaw',
    gadgetType: 'electroclaw',
    charges: 2,
    cooldown: 4.0,
    speed: 1,
    armor: 3,
    playstyle: 'Electrify roof hatches and multiple reinforced walls simultaneously by hiding the claw in concealed spots.'
  },
  {
    id: 'mozzie',
    name: 'Mozzie',
    role: 'Intel / Anti-Drone',
    side: 'def',
    color: 0xe67e22,
    ability: 'Pest Launcher — fires autonomous robotic spiders that leap onto attacker recon drones and hijack them into defender surveillance cameras.',
    gadgetName: 'Pest Autonomous Drone Hijacker',
    gadgetType: 'pest_launcher',
    charges: 3,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Place pests at drone holes and stairways. Stolen drones become valuable defender cameras.'
  },
  {
    id: 'warden',
    name: 'Warden',
    role: 'Anchor / Anti-Visual',
    side: 'def',
    color: 0x27ae60,
    ability: 'Glance Smart Glasses — activates tactical eyewear granting complete immunity to flashbangs and clear vision through smoke clouds.',
    gadgetName: 'Glance Smart Glasses',
    gadgetType: 'smart_glasses',
    charges: 1,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Hold angles when attackers throw smoke or flashbangs; see right through the smoke to eliminate executing attackers.'
  },
  {
    id: 'goyo',
    name: 'Goyo',
    role: 'Area Denial',
    side: 'def',
    color: 0xd9534f,
    ability: 'Volcán Canister — deploys fire canisters onto barricades or deployable shields; bursting the canister blankets the area in 20s of raging fire.',
    gadgetName: 'Volcán Incendiary Canister',
    gadgetType: 'volcan_shield',
    charges: 4,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Mount Volcán canisters on doorways and shoot them when attackers try to push, creating impassable fiery choke points.'
  },
  {
    id: 'wamai',
    name: 'Wamai',
    role: 'Anti-Gadget / Support',
    side: 'def',
    color: 0x16a085,
    ability: 'Mag-NET — throws magnetic suction discs that attach anywhere; attracts incoming grenades and projectiles and safely detonates them away.',
    gadgetName: 'Mag-NET System',
    gadgetType: 'magnet_defense',
    charges: 4,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Place Mag-NETs around corners and ceilings to redirect attacker grenades away from defensive anchors.'
  },
  {
    id: 'oryx',
    name: 'Oryx',
    role: 'Roamer / Mobility',
    side: 'def',
    color: 0x7f8c8d,
    ability: 'Remah Dash — performs explosive muscular sprint dash; smashes clean through soft walls without tools and knocks down shield operators.',
    gadgetName: 'Remah Dash Kinetic Burst',
    gadgetType: 'remah_dash',
    charges: 3,
    cooldown: 4.0,
    speed: 3,
    armor: 1,
    playstyle: 'Burst through soft walls for surprise flanks and tackle shield operators to the ground for quick eliminations.'
  },
  {
    id: 'melusi',
    name: 'Melusi',
    role: 'Crowd Control / Intel',
    side: 'def',
    color: 0x2ecc71,
    ability: 'Banshee — deploys sonic defense pylon on walls/floors; emits deafening sonic hum that significantly slows down approaching attackers.',
    gadgetName: 'Banshee Sonic Defense Pylon',
    gadgetType: 'banshee_slow',
    charges: 3,
    cooldown: 3.0,
    speed: 3,
    armor: 1,
    playstyle: 'Place Banshees along common attack corridors. The loud hum alerts the team and traps attackers in slow motion.'
  },
  {
    id: 'aruni',
    name: 'Aruni',
    role: 'Area Denial / Site Setup',
    side: 'def',
    color: 0xe74c3c,
    ability: 'Surya Gate — mounts laser energy grid over doors, windows, and reinforced walls; incinerates incoming projectiles and burns intruders for 30 dmg.',
    gadgetName: 'Surya Laser Gate',
    gadgetType: 'surya_gate',
    charges: 3,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Mount Surya laser gates over entryways to force attackers to sacrifice utility or take heavy damage to pass.'
  },
  {
    id: 'thunderbird',
    name: 'Thunderbird',
    role: 'Support / Anchor',
    side: 'def',
    color: 0x3498db,
    ability: 'Kona Station — deploys automated medical station that periodically dispenses healing stim shots (+30 HP) to any wounded defender in range.',
    gadgetName: 'Kona Automated Medical Station',
    gadgetType: 'kona_station',
    charges: 3,
    cooldown: 3.0,
    speed: 3,
    armor: 1,
    playstyle: 'Set up Kona stations in safe anchor bunkers so teammates can rotate back to heal during the round.'
  },
  {
    id: 'thorn',
    name: 'Thorn',
    role: 'Trapper',
    side: 'def',
    color: 0x9b59b6,
    ability: 'Razorbloom Shell — throws magnetic device that adheres to surfaces; when an attacker approaches, it arms with a sharp alarm and detonates lethal shrapnel.',
    gadgetName: 'Razorbloom Shrapnel Shell',
    gadgetType: 'razorbloom',
    charges: 3,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Hide Razorblooms beneath barbed wire or around corners; force attackers to scramble into defender crossfire.'
  },
  {
    id: 'azami',
    name: 'Azami',
    role: 'Site Setup / Support',
    side: 'def',
    color: 0x34495e,
    ability: 'Kiba Barrier — throws modified kunai knives that expand into bulletproof solidified concrete foam discs, sealing holes and creating custom cover.',
    gadgetName: 'Kiba Solidifying Barrier Kunai',
    gadgetType: 'kiba_barrier',
    charges: 5,
    cooldown: 4.0,
    speed: 2,
    armor: 2,
    playstyle: 'Patch breached walls, block lines of sight, and create brand-new bulletproof cover anywhere on site.'
  },
  {
    id: 'solis',
    name: 'Solis',
    role: 'Intel / Roamer',
    side: 'def',
    color: 0x1abc9c,
    ability: 'SPEC-IO — activates augmented reality electro-scanner helmet; detects, highlights, and marks all active attacker electronics through walls.',
    gadgetName: 'SPEC-IO Electro-Scanner',
    gadgetType: 'spec_io',
    charges: 1,
    cooldown: 6.0,
    speed: 2,
    armor: 2,
    playstyle: 'Scan through ceilings during prep phase to hunt down attacker drones, and spot attackers on their drone phones.'
  },
  {
    id: 'fenrir',
    name: 'Fenrir',
    role: 'Trapper / Crowd Control',
    side: 'def',
    color: 0x8e44ad,
    ability: 'F-NATT Dread Mine — deploys release pods releasing hallucinogenic dread gas that severely limits attacker vision to just a few feet.',
    gadgetName: 'F-NATT Dread Mine',
    gadgetType: 'dread_mine',
    charges: 5,
    cooldown: 2.0,
    speed: 2,
    armor: 2,
    playstyle: 'Activate Dread Mines when attackers enter entryways, blinding them in purple fog for easy takedowns.'
  },
  {
    id: 'tubarao',
    name: 'Tubarão',
    role: 'Area Denial / Anti-Gadget',
    side: 'def',
    color: 0x0284c7,
    ability: 'Zoto Canister — throws cryogenic canister that bursts into liquid nitrogen freeze zone; freezes gadgets, delays breach charges, and leaves icy footsteps.',
    gadgetName: 'Zoto Cryogenic Canister',
    gadgetType: 'zoto_canister',
    charges: 4,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Throw Zoto canisters onto reinforced walls to freeze Thermite and Ace breach charges, giving Bandit time to shock them.'
  },
  {
    id: 'skopos',
    name: 'Skopós',
    role: 'Remote Presence / Intel',
    side: 'def',
    color: 0x2c3e50,
    ability: 'V10 Pantheon Shells — deploys twin combat robot shells; swap consciousness instantly between the active chassis and the stationary sentry chassis.',
    gadgetName: 'V10 Pantheon Shell Transfer',
    gadgetType: 'pantheon_shells',
    charges: 1,
    cooldown: 3.0,
    speed: 2,
    armor: 2,
    playstyle: 'Position one robot shell on Site A and the other on Site B, instantly switching control wherever the attack hits.'
  },
  {
    id: 'sentry',
    name: 'Sentry',
    role: 'Support / Site Setup',
    side: 'def',
    color: 0xbdc3c7,
    ability: 'Defensive Support System — rapid defensive fortification kit carrying extra barricades, deployable shield, and tactical ammo replenishment.',
    gadgetName: 'Fortification Support Kit',
    gadgetType: 'sentry_system',
    charges: 2,
    cooldown: 5.0,
    speed: 2,
    armor: 2,
    playstyle: 'Lock down site entrances with extra fortifications and supply teammates with defensive reinforcements.'
  },
  {
    id: 'noor',
    name: 'Noor',
    role: 'Area Control',
    side: 'def',
    color: 0xd35400,
    ability: 'Horus Lance — throws acoustic denial lance that embeds into walls and projects high-frequency disruption field through the barrier.',
    gadgetName: 'Horus Acoustic Lance',
    gadgetType: 'horus_lance',
    charges: 2,
    cooldown: 5.0,
    speed: 2,
    armor: 2,
    playstyle: 'Mount Horus lances on walls to scramble attacker visibility and acoustic clarity through key doorways.'
  }
];

export const ALL_OPERATORS: OperatorDef[] = [...ATTACKERS, ...DEFENDERS];

// Backwards-compatible export
export const OPERATORS = ALL_OPERATORS;

export function getOperatorById(id: string): OperatorDef {
  return ALL_OPERATORS.find(op => op.id === id) || ALL_OPERATORS[0];
}
